#!/usr/bin/env bash
#
# Build tests for MKS Robin nano v3
# (STM32F407VET6)
#

# exit on first failure
set -e

#
# MKS Robin nano v3 Emulated DOGM TFT
#
use_example_configs "MKS Robin nano v3.0/Config example for suport sd card"
exec_test $1 $2 "MKS Robin nano v3 Emulated DOGM TFT" "$3"

# cleanup
restore_configs
